### ISSUE TITLE
2.9.3 not automatically generating and sending an attachment

### ISSUE THREAD

**Issue by el-presidente** [baselbers/woocommerce-pdf-invoices#204]
With the new update it's not generating the PDF and automatically adding an attachment anymore.

I can see from my sent emails that it stopped working when I updated the plugin, but I have just encountered the bug now. Others are also seeing this:

https://wordpress.org/support/topic/invoice-not-attaching/

**Comment by EmilEriksen** [comment]
Did you check the settings? We had the same issue. The data structure for the attach to email setting was changed in a previous version but the data wasn't properly migrated upon upgrading so suddenly our invoices were attaching to the wrong emails. Turned out we simply needed to update the setting on the settings page. Of course this shouldn't happen but at least that fixes it
