### ISSUE TITLE
Multistore/Multisite compatibility

### ISSUE THREAD

**Issue by baselbers** [baselbers/woocommerce-pdf-invoices#219]
Fatal error. Can't find uploads folder.

**Comment by chrisdebruine** [comment]
i am the one who emailed about this issue... 

Just found out that if i copy the folder in the uploads section on FTP to the 2nd store the problem is solved. just did 12 invoices on both stores and its working and saving in the correct folders on FTP. i did change the invoice prefix on the second store... Hopefully this helps you narrowing dong the issue! let me know...

**Comment by baselbers** [comment]
Think that the plugin will have to create multiple upload dirs. Never used multisite setup, so will have to dig into it.

**Comment by baselbers** [comment]
88b054b278710009eedc3c24a6a743da524bd18e
